services:

  Akeneo\Platform\Installer\Application\ResetElasticsearchIndexes\ResetElasticSearchIndexesHandler:
    arguments:
      - '@Akeneo\Platform\Installer\Infrastructure\Query\Elasticsearch\ResetIndexes'
